import os
import argparse
import random
import numpy as np
from tqdm import tqdm

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

def parse_args():
    parser = argparse.ArgumentParser(description="Train a Linear/MLP Projection for Semantic Alignment or Baseline.")
    
    # Dataset and Paths
    parser.add_argument('--dataset', type=str, required=True, help='Dataset name (e.g., movies, books, games)')
    parser.add_argument('--data_root', type=str, default='./dataset', help='Root directory for datasets')
    parser.add_argument('--output_root', type=str, default='./saved', help='Root directory for saved models')
    
    # Model Hyperparameters
    parser.add_argument('--proj_dim', type=int, default=64, help='Dimension of the projection output')
    parser.add_argument('--hidden_dim', type=int, default=512, help='Hidden dimension if using MLP (not used in Linear)')
    parser.add_argument('--temperature', type=float, default=0.1, help='Temperature for InfoNCE loss')
    
    # Training Hyperparameters
    parser.add_argument('--epochs', type=int, default=100, help='Number of training epochs')
    parser.add_argument('--batch_size', type=int, default=2048, help='Batch size')
    parser.add_argument('--lr', type=float, default=1e-3, help='Learning rate')
    parser.add_argument('--weight_decay', type=float, default=0.0, help='Weight decay')
    parser.add_argument('--neg_per_pos', type=int, default=256, help='Number of negative samples per positive sample')
    parser.add_argument('--patience', type=int, default=3, help='Early stopping patience')
    
    # System
    parser.add_argument('--num_workers', type=int, default=4, help='Number of data loader workers')
    parser.add_argument('--seed', type=int, default=2020, help='Random seed')
    
    return parser.parse_args()

# ================= Data Loading =================
def load_data(args, device):
    dataset_path = os.path.join(args.data_root, args.dataset)
    # Assumes preprocessing has generated this file
    item_emb_path = os.path.join(dataset_path, f"{args.dataset}_item_embeddings.npy")
    
    print("1. Loading raw item embeddings...")
    if not os.path.exists(item_emb_path):
        raise FileNotFoundError(f"File not found: {item_emb_path}")

    raw_item_embs = np.load(item_emb_path).astype(np.float32)  # [n_items, d]

    # Normalize input vectors (Consistent with baseline protocols)
    norms = np.linalg.norm(raw_item_embs, axis=1, keepdims=True)
    item_embeddings = raw_item_embs / (norms + 1e-10)

    def read_inter(suffix):
        data = {}
        path = os.path.join(dataset_path, f"{args.dataset}.{suffix}.inter")
        if not os.path.exists(path):
            print(f"Warning: {path} does not exist")
            return data
        with open(path, "r", encoding="utf-8") as f:
            next(f) # skip header
            for line in f:
                parts = line.strip().split("\t")
                if len(parts) < 2:
                    continue
                # The split script outputs tokens, but if we need internal IDs for training 
                # we might need to map them back or assume the script outputted indices.
                # Assuming here the input files are the ones generated by LightGCN or pre-mapped.
                # If using the 'preprocess_split.py' output (tokens), you'd need a token2id map here.
                # For simplicity, assuming pre-mapped integers for this training script.
                try:
                    u, i = int(parts[0]), int(parts[1])
                    data.setdefault(u, []).append(i)
                except ValueError:
                    continue # header or malformed
        return data

    print("2. Reading interaction data...")
    train_set = read_inter("train")
    valid_set = read_inter("valid")
    test_set  = read_inter("test")

    all_users = set(train_set.keys()) | set(valid_set.keys()) | set(test_set.keys())
    n_users = (max(all_users) + 1) if all_users else 0
    n_items = len(item_embeddings)
    dim = item_embeddings.shape[1]

    print(f"   Users: {n_users}, Items: {n_items}, Dim: {dim}")

    # Compute User Semantic Vectors (Mean Pooling on TRAIN)
    print("3. Computing User Semantic Vectors (Mean Pooling on Train)...")
    user_sem = np.zeros((n_users, dim), dtype=np.float32)
    for u, items in tqdm(train_set.items(), desc="Init Users"):
        valid_items = [i for i in items if 0 <= i < n_items]
        if not valid_items:
            continue
        vecs = item_embeddings[valid_items]
        mean_vec = np.mean(vecs, axis=0)
        norm = np.linalg.norm(mean_vec)
        if norm > 1e-10:
            user_sem[u] = mean_vec / norm

    return item_embeddings, user_sem, train_set, valid_set, test_set

# ================= Dataset: Returns only (u, pos) =================
class UPDataset(Dataset):
    def __init__(self, train_set):
        self.samples = []
        for u, items in train_set.items():
            for i in items:
                self.samples.append((u, i))

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        return self.samples[idx]

# ================= Model: Learnable Projection W =================
class LinearWModel(nn.Module):
    def __init__(self, item_sem_np, user_sem_np, out_dim, temperature=0.1):
        super().__init__()
        item_sem = torch.from_numpy(item_sem_np)   # [n_items, d]
        user_sem = torch.from_numpy(user_sem_np)   # [n_users, d]
        self.register_buffer("item_sem", item_sem)
        self.register_buffer("user_sem", user_sem)

        in_dim = item_sem.shape[1]
        if out_dim is None:
            out_dim = in_dim

        self.in_dim = in_dim
        self.out_dim = out_dim
        self.temperature = float(temperature)

        # Simple Linear Projection (can be replaced with MLP for non-linear probes)
        self.W = nn.Linear(in_dim, out_dim, bias=False)
        
        # Initialize W close to identity if dims match (optional optimization)
        if in_dim == out_dim:
            self._init_W_identity_like()

    def _init_W_identity_like(self):
        with torch.no_grad():
            self.W.weight.zero_()
            m = min(self.out_dim, self.in_dim)
            self.W.weight[:m, :m].copy_(torch.eye(m))

    def map_norm(self, x):
        y = self.W(x)
        return F.normalize(y, p=2, dim=-1)

    def get_user_vec(self, uids):
        base = self.user_sem[uids]
        return self.map_norm(base)

    def get_item_vec(self, iids):
        base = self.item_sem[iids]
        return self.map_norm(base)

    def forward_infonce(self, uids, pos_iids, neg_iids):
        """
        logits = [u·pos/t, u·neg/t...]
        """
        u = self.get_user_vec(uids)            # [B, d']
        pos = self.get_item_vec(pos_iids)      # [B, d']
        neg = self.get_item_vec(neg_iids.reshape(-1)).view(
            neg_iids.shape[0], neg_iids.shape[1], -1
        )                                      # [B, NEG, d']

        pos_logit = torch.sum(u * pos, dim=-1, keepdim=True) / self.temperature  # [B,1]
        neg_logit = torch.einsum("bd,bnd->bn", u, neg) / self.temperature        # [B,NEG]
        logits = torch.cat([pos_logit, neg_logit], dim=1)                         # [B,1+NEG]
        labels = torch.zeros(uids.shape[0], dtype=torch.long, device=uids.device)
        return F.cross_entropy(logits, labels)

    @torch.no_grad()
    def export_all_embeddings(self, device):
        u = self.map_norm(self.user_sem.to(device))
        i = self.map_norm(self.item_sem.to(device))
        return u, i

# ================= Utils: Vectorized Masking =================
def build_train_pos_index(train_set):
    """
    Pre-process train positives into CSR format for fast masking during evaluation.
    """
    max_u = max(train_set.keys()) if train_set else -1
    n_users = max_u + 1

    lengths = np.zeros(n_users, dtype=np.int64)
    total = 0
    for u, items in train_set.items():
        l = len(items)
        lengths[u] = l
        total += l

    offsets = np.zeros(n_users + 1, dtype=np.int64)
    np.cumsum(lengths, out=offsets[1:])

    items_concat = np.empty(total, dtype=np.int64)
    cursor = 0
    for u in range(n_users):
        items = train_set.get(u, [])
        if items:
            items_concat[cursor:cursor+len(items)] = np.array(items, dtype=np.int64)
            cursor += len(items)

    return offsets, items_concat

def mask_train_positives_in_scores(scores, batch_uids, offsets, items_concat, chunk_start, chunk_end):
    """
    Masks training positives in the score matrix (sets them to -inf).
    """
    device = scores.device
    bu = torch.as_tensor(batch_uids, dtype=torch.long, device="cpu")
    
    row_ids = []
    col_ids = []

    for r, u in enumerate(bu.tolist()):
        if u >= len(offsets) - 1:
            continue
        s = offsets[u]
        e = offsets[u + 1]
        if e <= s:
            continue
        items = items_concat[s:e]
        
        # Only mask items falling within the current chunk
        m = items[(items >= chunk_start) & (items < chunk_end)]
        if m.size == 0:
            continue
        row_ids.append(np.full(m.shape[0], r, dtype=np.int64))
        col_ids.append(m - chunk_start)

    if not row_ids:
        return

    row_ids = torch.from_numpy(np.concatenate(row_ids)).to(device=device, dtype=torch.long)
    col_ids = torch.from_numpy(np.concatenate(col_ids)).to(device=device, dtype=torch.long)

    scores[row_ids, col_ids] = -float("inf")

# ================= Evaluation =================
@torch.no_grad()
def evaluate_all_ranking_fast(model, train_set, target_set, offsets, items_concat,
                             n_items, device, Ks=(10, 20),
                             user_batch=512, item_chunk=20000, min_interactions=0):
    model.eval()
    if not target_set:
        return {k: 0.0 for k in Ks}

    uids = [u for u in target_set.keys() if len(train_set.get(u, [])) >= min_interactions]
    if not uids:
        return {k: 0.0 for k in Ks}

    all_user_vecs, all_item_vecs = model.export_all_embeddings(device=device)
    all_item_vecs_t = all_item_vecs.t().contiguous()

    K_max = max(Ks)
    results = []

    for us in range(0, len(uids), user_batch):
        batch_uids = uids[us:us + user_batch]
        bu = torch.tensor(batch_uids, dtype=torch.long, device=device)
        uvec = all_user_vecs[bu]

        top_scores = torch.full((uvec.size(0), K_max), -float("inf"), device=device)
        top_items = torch.full((uvec.size(0), K_max), -1, device=device, dtype=torch.long)

        for cs in range(0, n_items, item_chunk):
            ce = min(cs + item_chunk, n_items)
            ivec_chunk_t = all_item_vecs_t[:, cs:ce]
            scores = uvec @ ivec_chunk_t

            mask_train_positives_in_scores(scores, batch_uids, offsets, items_concat, cs, ce)
            if cs <= 0 < ce:
                scores[:, 0 - cs] = -float("inf") # Mask pad item 0

            chunk_k = min(K_max, scores.size(1))
            c_scores, c_idx = torch.topk(scores, k=chunk_k, dim=1)
            c_items = c_idx + cs

            merged_scores = torch.cat([top_scores, c_scores], dim=1)
            merged_items = torch.cat([top_items, c_items], dim=1)
            new_scores, new_pos = torch.topk(merged_scores, k=K_max, dim=1)
            new_items = torch.gather(merged_items, 1, new_pos)
            top_scores, top_items = new_scores, new_items

        top_items_cpu = top_items.cpu().numpy()
        for r, u in enumerate(batch_uids):
            gt = set(target_set.get(u, []))
            if not gt:
                continue
            recs = {}
            for k in Ks:
                hit = len(set(top_items_cpu[r, :k]) & gt)
                recs[k] = hit / len(gt)
            results.append(recs)

    if not results:
        return {k: 0.0 for k in Ks}
    return {k: float(np.mean([r[k] for r in results])) for k in Ks}

# ================= Main =================
def main():
    args = parse_args()
    
    # Fix Seeds
    random.seed(args.seed)
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)
    
    if not os.path.exists(args.output_root):
        os.makedirs(args.output_root)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")
    
    # Load Data
    # Note: Requires item_embeddings.npy and split .inter files
    item_sem, user_sem, train_set, valid_set, test_set = load_data(args, device)
    
    n_items = item_sem.shape[0]
    in_dim = item_sem.shape[1]

    offsets, items_concat = build_train_pos_index(train_set)

    dataset = UPDataset(train_set)
    loader = DataLoader(
        dataset,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=args.num_workers,
        pin_memory=True,
        drop_last=True,
    )

    out_dim = args.proj_dim
    model = LinearWModel(item_sem, user_sem, out_dim=out_dim, temperature=args.temperature).to(device)
    optimizer = optim.Adam(model.W.parameters(), lr=args.lr, weight_decay=args.weight_decay)
    
    scaler = torch.cuda.amp.GradScaler(enabled=(device.type == "cuda"))

    # Initial Eval
    Ks = [10, 20]
    print("\n>>> Baseline (Init W) Validation...")
    base_valid = evaluate_all_ranking_fast(
        model, train_set, valid_set, offsets, items_concat,
        n_items=n_items, device=device, Ks=Ks
    )
    print("   " + " | ".join([f"Recall@{k}: {base_valid[k]:.4f}" for k in Ks]))

    key = 20
    best_val = base_valid[key]
    best_epoch = 0
    no_improve = 0
    
    tmp_path = os.path.join(args.output_root, f"{args.dataset}_tmp.pth")

    print("\n>>> Training Projection ...")
    
    for epoch in range(1, args.epochs + 1):
        model.train()
        total_loss = 0.0
        steps = 0

        for u, pos in tqdm(loader, desc=f"Epoch {epoch}"):
            u = u.to(device, non_blocking=True).long()
            pos = pos.to(device, non_blocking=True).long()

            # Fast Negative Sampling on GPU
            negs = torch.randint(1, n_items, (u.size(0), args.neg_per_pos), device=device)
            
            # Simple collision check
            eq = (negs == pos.unsqueeze(1))
            if eq.any():
                negs = torch.where(eq, (negs + 1) % n_items, negs)
                negs = torch.where(negs == 0, torch.ones_like(negs), negs)

            optimizer.zero_grad(set_to_none=True)

            with torch.cuda.amp.autocast(enabled=(device.type == "cuda")):
                loss = model.forward_infonce(u, pos, negs)

            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()

            total_loss += loss.item()
            steps += 1

        print(f"Epoch {epoch} Loss: {total_loss/max(1,steps):.4f}")

        # Validation
        valid = evaluate_all_ranking_fast(
            model, train_set, valid_set, offsets, items_concat,
            n_items=n_items, device=device, Ks=Ks
        )
        print("   Valid: " + " | ".join([f"Recall@{k}: {valid[k]:.4f}" for k in Ks]))

        if valid[key] > best_val:
            best_val = valid[key]
            best_epoch = epoch
            no_improve = 0
            torch.save(model.state_dict(), tmp_path)
            print(">>> New Best saved.")
        else:
            no_improve += 1
            print(f">>> No improve {no_improve}/{args.patience}")
            if no_improve >= args.patience:
                print(">>> Early stop.")
                break

    # Load Best and Test
    if os.path.exists(tmp_path):
        model.load_state_dict(torch.load(tmp_path, map_location=device))
        os.remove(tmp_path)

    print(f"\nBest Valid Recall@{key}: {best_val:.4f} (Epoch {best_epoch})")

    print("\n>>> Testing ...")
    test = evaluate_all_ranking_fast(
        model, train_set, test_set, offsets, items_concat,
        n_items=n_items, device=device, Ks=Ks
    )
    print("   " + " | ".join([f"Recall@{k}: {test[k]:.4f}" for k in Ks]))

    # Export Embeddings
    save_dir = os.path.join(args.data_root, args.dataset)
    os.makedirs(save_dir, exist_ok=True)
    output_user = os.path.join(save_dir, f"{args.dataset}_user_embeddings-proj64.npy")
    output_item = os.path.join(save_dir, f"{args.dataset}_item_embeddings-proj64.npy")
    
    model.eval()
    with torch.no_grad():
        u_all, i_all = model.export_all_embeddings(device=device)
        u_all = u_all.cpu().numpy().astype(np.float32)
        i_all = i_all.cpu().numpy().astype(np.float32)

    np.save(output_user, u_all)
    np.save(output_item, i_all)
    print(f"Saved projected embeddings to {args.output_root}")

if __name__ == "__main__":
    main()